# Generated by Django 4.2 on 2025-10-31 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_alter_course_id_alter_question_id_alter_result_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_file',
            field=models.FileField(blank=True, help_text='Upload question file (PDF, PPT, DOC, XLS)', null=True, upload_to='question_files/'),
        ),
    ]
