# Generated by Django 4.2 on 2025-10-31 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_student_assigned_teacher_alter_student_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='assigned_teacher',
            new_name='teacher',
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='student',
            name='mobile',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/StudentProfilePic/'),
        ),
    ]
